# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            victor g.
tagline:          composer
description:      welcome to my world! 
url:              victorgrand.github.io
baseurl:          /

author:
  name:           'Victor Grand'
  url:            https://twitter.com/VictorGrand

paginate:         5
plugins: [jekyll-paginate]

highlighter: pygments

# Custom vars
version:          2.1.0

github:           https://github.com/VictorGrand

